V1.1.1/feature/client api (#194)
* Chore: Added client functionality interface

* Chore: Added Client ctor and fields

* Refactor: Removed unneeded explicit dtor

* Chore: Added ClientException

* Refactor: Made make_userset return userset ID

* Doc: Added doc of IClient methods

* Refactor: Made get_userset_members accept two callback functions (one for owners one for regs)

* Fix: Made encrypt() accept userset ID

* Chore: Added connection utilities to Client class

* Chore: Added utility Client::post

* Chore: Added ClientUtils::locate_user_profile_file()

* Chore: Added client storage utilities

* Feat: Implemented signup, login, logout

* Feat: Added login check in post

* Feat: Implemented make_userset

* Feat: Implemented get_usersets and get_userset_members

* Refactor: Replaced autos with explicit packet types (for better intellisense)

* Chore: Added utility find_profile_record_by_userset_id

* Refactor: Changed Client class to regard ciphertext type as Ciphertext rather than Buffer

* Feat: Implemented encrypt

* Feat: Implemented decrypt

* Refactor: Made queued packet handler accept factory instead of underlying handler type

* Refactor: Made Client class use QueuedPacketHandler

* Refactor: Moved packet handler emplace logic to utility emplace_packet_handler to reduce code duplication

* Refactor: Added utility post method which accepts packet sender

* Chore: Added infrastructure for background updates

* Refactor: Renamed update() to update_callback()

* Feat: Added force_update

* Chore: Added infrastructure for handling different update records

* Refactor: Method implementation order

* Chore: Added utility add_profile_record

* Feat: Implemented handle_added_as_reg_member and handle_added_as_owner

* Chore: Added infrastructure for handle_on_lookup

* Fix: Added missing ampersand

* Chore: Added infrastructure for handle_to_decrypt

* Refactor: Added internal pending decryptions map

* Refactor: Renamed static post to post_on

* Fix: Added storage clearout in logout

* Feat: Implemented handle_finished_decryption

* Feat: Implemented request_participance

* Feat: Implemented participate

* Feat: Added iter_profile

* Chore: Removed obsolete profile API functions

* Doc: Added missing doc login note on decrypt

* Chore: Added client API function declarations

* Refactor: Replaced buffer with bytes view in ECGroup::decode()

* Fix: API function declarations to consider c3a and c3b

* Fix: Missing SENC_NOTHROW

* Style: Shortened declaration

* Refactor: Modified API declarations to use buffer handles

* Feat: Implemented ciphertext API functions

* Refactor: Removed duplicated include

* Chore: Added Client move ctor

* Refactor: Moved parse_ip to utils

* Fix: Added missing callback param to connect

* Fix: Removed extensive param from call

* Fix: Arrow to dot for reference

* Fix: Typo "shardsIds"->"shardsIDs"

* Fix: Missing std::move

* Fix: Missing factory arg

* Fix: Removed reference from port param in Client ctor

* Feat: Implemented Connect and Disconnect

* Doc: Changed doc of IterUserProfile to state NULL on success

* Refactor: Changed API function signatures to be able to handle errors properly

* Feat: Added support of null in FreeHandle

* Chore: Added Error::ret_null_or_err

* Refactor: Made Client::iter_profile accept std::function instead of raw function pointer

* Fix: Param name "hProfile"->"hClient"

* Feat: Implemented client user manage API functions (login, signup, logout, iter)

* Refactor: Modified existing API function implementations to call get() preemptively and name variables accordingly

* Perf: Added missing lambda captures

* Fix: Moved definition of template func to header

* Fix: Changed ret type from Error to Handle to fix compilation error

* Fix: Added missing param usersetID of API function GetUserSetMembers

* Feat: Implemented userset-related API functions

* Feat: Implemented API functions Encrypt and Decrypt

* Feat: Implemented API function ForceUpdate

* Refactor: Replaced all new_instance calls with ret_new

* Feat: Added context support for callback of Connect

* Feat: Added context support for callback of IterUserProfile

* Feat: Added context support for callback of GetUserSets

* Feat: Added context support for callback of GetUserSetMembers

* Test: Added infrastructure for client API tests

* Refactor: Modified MakeUserSet to accept general uint and check for valid bounds

* Refactor: Added SENC prefix to all API functions

* Chore: Added struct SENC_Handle

* Feat: Added empty callback option to SENC_Connect

* Feat: Added empty callback option to SENC_IterUserProfile

* Feat: Added empty callback option to SENC_GetUserSets

* Feat: Added empty callback option to SENC_GetUserSetMembers

* Chore: Added SENC_Handle default ctor and copy semantics

* Fix: Fixed SENC_Handle operator= not freeing old handle

* Refactor: Moved SENC_Handle implementation to .cpp

* Fix: Added missing include stdbool.h for C compatibility

* Test: Added RoundTripFlow test

* Test: Removed unused var status in test

* Fix: Moved SEND_Handle implementation back to .h

* Refactor: Made operator uintptr_t of SEND_Handle be constexpr

* Fix: Replaced copy ctor of SEND_Handle with move ctor

* Build: Modified test build to internally compile DLL functions instead of linking DLL

* Refactor: Added noexcept

* Fix: Added null guard for _sync in queued packet handler dtor

* Build: Added separate linkage confic for tests

* Fix: _sync not being initialized, and not being moved properly

* Refactor: Made _sync be on stack

* Fix: Maded SENC_HasError() return false for null

* Test: Fixed test using owners callback for regs

* Test: Fixed extra null termination in test

* Test: Made vector refs const

* Fix: Exceptions in updates thread

* Test: Fixed test not properly testing all owners vector

* Refactor: Changed optional jthread _queueThread back to plain jthread

* Refactor: Made _sync be first field of queued packet handler

* Fix: Fixed queued packet handler fields being potentially moved mid operations (added dummy move ctor for Sync)

* Test: Added SignupLoginLogout test

* Refactor: Renamed SENC_Login to SENC_LogIn

* Refactor: Renamed SENC_Logout to SENC_LogOut